Fixing the amount by correct handling the number of BigUint decimals
multiversx/mx-bridge-eth-sc-rs pull request #139
Opened 2023-03-09 12:38 UTC by alyn509

2023-03-09 13:36 UTC, sasurobert commented on bridged-tokens-wrapper/src/lib.rs
> +        let universal_token_decimals = self.token_decimals_num(&payment_token).get();
you could make an internal function for the conversion and call the same function on both wrap and unwrap functions.

2023-03-09 15:09 UTC, alyn509 commented on bridged-tokens-wrapper/src/dfp_big_uint.rs
> +    pub fn trunc(&self) -> Self {
for test purposes was introduced. The whole struct will be moved in the framework so don't worry about it

2023-03-09 15:19 UTC, sasurobert reviewed
still some tests are failing

2023-03-09 15:36 UTC, alyn509 commented
> still some tests are failing

2023-03-09 15:45 UTC, sasurobert approved these changes

2023-03-10 10:48 UTC, sasurobert commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
delete commented stuff. Why do we need .vscode folder here ?

2023-03-10 11:10 UTC, sasurobert approved these changes

2023-03-10 14:05 UTC, dragos-rebegea approved these changes

2023-03-10 14:45 UTC, andrei-marinica submitted a review, later dismissed

2023-03-10 14:45 UTC, andrei-marinica commented on bridged-tokens-wrapper/mandos/blacklist_token.scen.json
> +                        "str:token_decimals_num|nested:str:WUSDC-abcdef": "0x06",
Values can be expressed in base 10, i.e. 6 and 18, respectively.

2023-03-10 14:45 UTC, andrei-marinica commented on bridged-tokens-wrapper/src/dfp_big_uint.rs
> +pub struct DFPBigUint<M: ManagedTypeApi> {
Add a comment saying that this is a Decimal Fixed Point Big Uint.

2023-03-10 15:22 UTC, iancudorinmarian commented on bridged-tokens-wrapper/src/dfp_big_uint.rs
> +    }
This function can be made more efficient:
- consume `self` and let the caller clone if they need to
- use early exit conditions (it's the most common, and it also makes the code more readable)

```suggestion
    pub fn convert(self, decimals: u32) -> Self {
            if self.num_decimals == decimals {
                 return self;
            }
    
        let new_bu=  if self.num_decimals > decimals { 
             let diff_decimals = self.num_decimals - decimals;
             self.bu / 10u64.pow(diff_decimals)
         else { 
               let diff_decimals = decimals - self.num_decimals;
               self.bu * 10u64.pow(diff_decimals)
         };
         
         DFPBigUint {
                bu: new_bu,
                num_decimals: decimals,
            }
```

2023-03-10 15:22 UTC, iancudorinmarian commented on bridged-tokens-wrapper/src/lib.rs
>              let new_payment = if !universal_token_id_mapper.is_empty() {
de-nest some of my old code:
```
if universal_token_id_mapper.is_empty() {  
       new_payments.push(payment); 
      continue; 
}

// the code in the original `if` here

new_payments.push(new_payment);
```

2023-03-10 15:22 UTC, iancudorinmarian commented on bridged-tokens-wrapper/src/lib.rs
> +        let amount = DFPBigUint::from_raw(amount, from_decimals);
please don't shadow the original `amount` argument. Rename this.

2023-03-10 15:49 UTC, sasurobert submitted a review, later dismissed

2023-03-10 16:58 UTC, iancudorinmarian commented on bridged-tokens-wrapper/src/lib.rs
> +            } else {
Remove the `else` entirely, you have `continue` in the `if`

2023-03-10 17:00 UTC, iancudorinmarian submitted a review, later dismissed

2023-03-10 17:15 UTC, andreibancioiu requested changes
Cargo lock is missing.

2023-03-10 18:03 UTC, sasurobert approved these changes

2023-03-10 18:10 UTC, andreibancioiu reviewed
Cargo lock present on the contract of interest :+1:

2023-03-10 18:16 UTC, andreibancioiu approved these changes

2023-03-10 18:17 UTC, merged